'\" t
.\" Copyright (c) 2016, valdemar lindberg
.\"
.\" %%%LICENSE_START(GPLv3+_DOC_FULL)
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 3 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, see
.\" <http://www.gnu.org/licenses/>.
.\" %%%LICENSE_END

.pc
.TH wprime 1 "03 November 2016" "1.0" "User Commands"
.SH NAME
wprime \- determine if 
.I n 
in
.I N
is a prime, when
.I n
!= 0.

.SH SYNOPSIS
.B wprime
\-dhd  [ -b n]

.B wprime
[
.B \-vsm
]

.SH DESCRIPTION
The 
.B wprime
program allow for computing if a natural number is a prime by utilzing Wilsom's theorem.

wprime has a time complexity of θ(n) = T(n-1). Which is because for each n,
Wilsom' theorem stats that p is prime if (p-1)! === 0modp. So the number of multiplication instruction is proportional to p.

.SH OPTIONS

.\.SH 1. COMMAND-LINE Options
.TP
.B \-b
Set number base for the input digit, default is 10. 
.TP
.B \-o
Sets number base to octacl which has the base 8.
.TP
.B \-v
Output version of the program and exit. 
.TP
.B \-H
Sets number base to hexadecimal which has the base 16.
.TP
.B \-h
Format the output in a human readable format.
.TP
.B \-d
Sets the number base to decimal which has the base 10.
.TP
.B \-m
Display the maximun number that is supported for determing if its a prime. 
.TP
.B \-s
Display the size of 
.B unsigned long long int
size in bits used for computing if its a prime or not.

.SH EXIT STATUS
If exist status is equal 0 than the program was exited successfully.


\#.SH EXAMPLES

\#wprime can take input from either from an argument or regular piping.

\#.B wprime
\#\-h 42
\#.TP
\#Will output in human readable for that 42 is not a prime number.
\#.TP
	
\#.B wprime
\#42 
\#.TP
\#Will output in boolean format. That is to say if 42 is prime, it output 1, if not 0. In this case 0.

\# echo "42" | wprime
\#.B wprime \-b
\#.TP
\#Will 
\#.TP
\#.B wprime \-v
\#.TP
\#Output version of 
\#.B wprime

.SH NOTES
Because the C compiler has a limit size for the 
.B unsigned long long int
data in bits. Thus there is a limit of how big prime number can be used. wprime uses 
.B unsigned long long int
, Which is at least 64-bits, depending of what platform. That is to say 1.8446744e+19 in base 10. So the biggest prime possible to compute is as followed.
2^(n/2) - 1, where n is the biggest integer in number of bits supported. This is an approximated value which has yet to be proven. So for a 64-bits integer, it would give 4294967295.


\#	.SH SEE ALSO
\#   A list of related commands or functions.
.SH BUGS
No known bugs.

.SH AUTHOR
	Valdemar Lindberg (voldiekami@gmail.com)
