name: Build LaTeX document - Wilson Prime
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: proof.tex
          latexmk_use_lualatex: true
          working_directory: doc

      - name: Move PDF file
        working-directory: doc
        run: mv -v proof.pdf Wilsom-Prime-Time-Space-Complexity-Reduction.pdf 

      - name: Upload Documents
        uses: actions/upload-artifact@v2
        with:
            name: Latex-Documents
            path: doc/Wilsom-Prime-Time-Space-Complexity-Reduction.pdf
